server:
  port: 8081
spring:
  profiles:
    group:
      "local": "local, jwt, oauth"
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/ole
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never # 초기 데이터 적재 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000${}

    defer-datasource-initialization: true  # 초기 데이터 적재 설정
